name: CI Lab 10

on:
  push:
    branches: [ main, master ]
    paths:
      - 'Lab 10/**'
      - '.github/workflows/ci-lab10.yml'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'Lab 10/**'
      - '.github/workflows/ci-lab10.yml'

jobs:
  ci:
    name: Lab 10 CI
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: "Lab 10/Dockerfile"

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'
          cache-dependency-path: "Lab 10/package-lock.json"

      - name: Install node dependencies
        working-directory: "Lab 10"
        run: npm ci

      - name: Run ESLint
        working-directory: "Lab 10"
        run: npm run lint

      - name: Run Unit Tests
        working-directory: "Lab 10"
        run: npm test

      - name: Start Integration Stack
        working-directory: "Lab 10"
        run: docker compose up -d

      - name: Setup Local AWS Resources
        working-directory: "Lab 10"
        run: |
          chmod +x ./scripts/local-aws-setup.sh
          ./scripts/local-aws-setup.sh

      - name: Run Integration Tests
        working-directory: "Lab 10"
        run: npm run test:integration

      - name: Stop Integration Stack
        if: always()
        working-directory: "Lab 10"
        run: docker compose down

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        env:
          DOCKERHUB_REPO: ${{ secrets.DOCKERHUB_USERNAME }}/fragments
          SHA_TAG: sha-${{ github.sha }}
        uses: docker/build-push-action@v6
        with:
          context: "Lab 10"
          file: "Lab 10/Dockerfile"
          push: true
          tags: ${{ env.DOCKERHUB_REPO }}:${{ env.SHA_TAG }}, ${{ env.DOCKERHUB_REPO }}:main, ${{ env.DOCKERHUB_REPO }}:latest

